version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx2048m
    container_name: jenkins
    ports:
      - "49001:8080"
    depends_on:
      - data
    volumes_from:
      - data
    restart: always
  data:
    build:
      context: ./
      dockerfile: Dockerfile-data
    volumes:
      - /jenkins/log:/var/log/jenkins
      - /jenkins/home:/var/jenkins_home
    container_name: jenkins-data
    restart: always
